### ISSUE TITLE
error during add new user

### ISSUE THREAD

**Issue by milenkocvijic** [senaite/senaite.lims#113] opened 2020-02-01 23:38 UTC
Hello, when I try to add new user, I get next message
![mail](https://user-images.githubusercontent.com/46087650/73600683-26dfec00-4554-11ea-9202-5970d40f6c69.PNG)

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module zope.formlib.form, line 868, in __call__
  Module five.formlib.formbase, line 50, in update
  Module zope.formlib.form, line 831, in update
  Module plone.fieldsets.form, line 30, in setUpWidgets
  Module zope.formlib.form, line 417, in setUpEditWidgets
  Module zope.schema._bootstrapfields, line 215, in get
  Module plone.app.controlpanel.mail, line 138, in get_email_from_name
AttributeError: email_from_name

How to fix it?
Thank you

**Comment by ramonski** [comment] 2020-02-04 10:08
Duplicate of https://github.com/senaite/senaite.core/issues/1465, closing

**Closed by ramonski** 2020-02-04 10:08 UTC
