### ISSUE TITLE
Senaite LIMS Application: Analysis file does not upload automatically, throws an error - 'No Changes Made'

### ISSUE THREAD

**Issue by singhamitabh** [senaite/senaite.lims#112] opened 2020-01-15 18:00 UTC
## Steps to reproduce
While importing the csv file for each analysis **[See attached Image A]**, the files aren’t submitted automatically. The user has to manually select the files and submit them, that results in an error with a yellow color page edit - 'No changes made'. **[See attached Image B]**

## Expected behavior
Expected Result - Upload the analysis csv file, and a successful submission would result in the status changing from "Unassigned" to "To be verified" and the resulting field is grayed out and locked.

## Current behavior
[Issue_1] Upload analysis file, the results import view does display the results (but the field isn't grayed out or locked). System behaves as the analysis file import wasn't successful because (the results appear to be stuck in a "saved" loop versus being "submitted" so the status is kept at "Unassigned”) **[See attached Image C]**
[Issue_2] The user then has to select those analysis files (from the checkbox on the left) with imported results and manually submit them which does not always result in successful submission.

## Screenshot (optional)
<img width="709" alt="A" src="https://user-images.githubusercontent.com/32080772/72458518-99dc1b00-377d-11ea-90a1-f0c6227cf144.png">
<img width="755" alt="B" src="https://user-images.githubusercontent.com/32080772/72458519-99dc1b00-377d-11ea-9b54-562739a92565.png">
<img width="702" alt="C" src="https://user-images.githubusercontent.com/32080772/72458520-99dc1b00-377d-11ea-956a-455cc431d4db.png">

**Comment by ramonski** [comment] 2020-01-15 18:06
Duplicate of https://github.com/senaite/senaite.core/issues/1496, please stick to this one issue @singhamitabh

**Closed by ramonski** 2020-01-15 18:06 UTC
