### ISSUE TITLE
Errors while installing.

### ISSUE THREAD

**Issue by devlinpadayachee** [senaite/senaite.lims#64] opened 2018-03-31 00:44 UTC
## Steps to reproduce
Install on Ubuntu 17

## Current behavior
Getting distribution for 'WeasyPrint==0.42'.
error: Setup script exited with error in WeasyPrint setup command: Invalid environment marker: python_version < "3.0"
An error occurred when trying to install WeasyPrint 0.42. Look above this message for any errors that were output by easy_install.
While:
  Installing client1.
  Getting distribution for 'WeasyPrint==0.42'.
Error: Couldn't install: WeasyPrint 0.42

## Expected behavior
Clean install

**Comment by ramonski** [comment] 2018-03-31 09:17
Duplicate of https://github.com/senaite/senaite.core/issues/560

**Closed** 2018-04-09 06:10 UTC

**Comment by devlinpadayachee** [comment] 2018-04-10 22:14
Thanks Sir I actually got it working
